kind: Kustomization
namespace: dev-mediawiki

bases:
  - ../../base

resources:
  - namespace.yaml

commonLabels:
  app: dev-mediawiki

patchesStrategicMerge:
  - mediawiki-route.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: mediawiki
  path: env-vars.yaml

