---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mediawiki
  namespace: mediawiki
  labels:
    app: mediawiki
    service: mediawiki
spec:
  host: dev-mediawiki.apps.ocp5.stormshift.coe.muc.redhat.com
  to:
    kind: Service
    name: mediawiki
  port:
    targetPort: web
