apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-mediawiki
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev-mediawiki
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/development
    repoURL: https://github.com/stefan-bergstein/mediawiki-kustomize-demo
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
