---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace : mediawiki
  labels:
    app: mariadb
    service: mariadb
spec:
  selector:
    app: mariadb
    service: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
      service: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
        service: mariadb
    spec:
      containers:
        - name: mariadb
          image: docker.io/centos/mariadb-102-centos7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeme
            - name: MYSQL_USER
              value: changeme
            - name: MYSQL_PASSWORD
              value: changeme
            - name: MYSQL_DATABASE
              value: changeme
          imagePullPolicy: Always
          workingDir: /
          ports:
            - containerPort: 3306
              protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mariadb
      volumes:
      - name: mariadb
        persistentVolumeClaim:
          claimName: mariadb
