apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      service: mediawiki
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mediawiki
        service: mediawiki
    spec:
      initContainers:
      - name: wait-for
        image: ghcr.io/patrickdappollonio/wait-for:latest
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        command:
          - /wait-for
        args:
          - --host="$(DB_HOST):$(DB_PORT)"
          - --verbose
      containers:
      - env:
        - name: MEDIAWIKI_SITE_SERVER
          value: mediawiki.apps.example.com
        - name: MEDIAWIKI_DB_SCHEMA
          value: mediawiki
        - name: MEDIAWIKI_SITE_NAME
          value: Mediawiki
        - name: MEDIAWIKI_SITE_LANG
          value: en
        - name: MEDIAWIKI_ADMIN_USER
          value: admin
        - name: MEDIAWIKI_ADMIN_PASS
          value: changeme
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: changeme
        - name: DB_PASSWORD
          value: changeme
        - name: DB_NAME
          value: changeme
        image: docker.io/ansibleplaybookbundle/mediawiki:latest
        imagePullPolicy: Always
        name: mediawiki
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /persistent
          name: mediawiki
      volumes:
      - name: mediawiki
        persistentVolumeClaim:
          claimName: mediawiki
