apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: mediawiki
  labels:
    app: mediawiki
    service: mediawiki
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: mediawiki
    service: mediawiki